### ISSUE TITLE
Reapply extension's wallpaper

### ISSUE THREAD

**Issue by postblue** [felipeborges/gnome-shell-extension-patterns#8]
I've installed the extension, found it great, played around, then disabled it, changed my wallpaper back to default, and now that I've re-enabled it, I've no more access to the patterns of the application, I'm sticked with my previous wallpaper. Maybe I'm doing it wrong, or the extension is missing an "apply pattern" button in the dialog box to reconfigure it. :)

**Comment by felipeborges** [comment]
@postblue you're right. Since the gsetting would be already set to the last time your wallpaper was set, the extension would take a day or week to update your wallpaper after you disable & enable it.

Thanks for reporting this issue!

**Comment by postblue** [comment]
Thank you for fixing it so quick! :)

**Comment by felipeborges** [comment]
You're welcome! I'll be submitting the up-to-date version to the extensions website soon.

**Comment by felipeborges** [comment]
I've reverted the commit that would fix this. Apparently GNOME Shell calls the extension's disabled() method when it isn't supposed to do.

**Comment by felipeborges** [comment]
The last release solves it. Thx!

**Comment by postblue** [comment]
Testing it, thx !
